### ISSUE TITLE
Expose called in master thread error using Electron + Vite

### ISSUE THREAD

**Issue by jmc07712** [Cloud-CNC/rollup-plugin-threads#3]
I have an electron application I have created using Vite and Vue 2 that I wish to use the ThreadsJS plugin for. Vite uses Rollup under the hood to do the bundling, and so I came across this package to do the Rollup Configuration setup for ThreadsJS for me.

## Overview of Error

I am experiencing the following error when following your example creation of a BlobWorker in the Renderer Process of my Electron applicaton:

```
Uncaught Error: expose() called in the master thread.
    at expose (:8080/@fs/W:/Lab/exp/moseq-reports/node_modules/.vite/threads.js?v=a8553044:2108)
    at :8080/components/Worker.ts:2
```

This error would indicate to me that perhaps the rollup configuration is picking up of the Worker files I have defined and therefore it is not bundling them to be imported properly into other files. It gets generated when the default import of the Worker file executes.

## Reproducing Error
I used [this ](https://github.com/deluze/electron-vue-template) repository to generate the boilerplate files for me. I then created a test component listed below called `Hello.vue` to test the ThreadsJS library.

The worker file I have created is called `Worker.ts` and is an exact clone of the Worker example in the README in this repository. For completeness, the file is copied below.

```js
// Worker.ts
//Imports
import { expose } from "threads";

//Expose the worker
expose((input: string) => {
    return `Worker received: ${input}`;
});

//Export (TypeScript only; replaced by bundled worker code)
export default "";
```

My usage of the Worker file is the following which is invoked in a Vue component in the Renderer Process of the electron application. The intended behavior is to launch the worker thread (mainly for testing purposes) via a button press and then simply print the output to the console (much like the example does in the README).

```js
// Hello.vue
<template>
    <div>
        <b-button v-on:click="this.buttonClick">Test</b-button>
    </div>
</template>

<script lang="ts">
import Vue from "vue";
import { BlobWorker, spawn, Thread } from "threads";
import WorkerText from "./Worker";

export default Vue.extend({
    methods: {
        buttonClick: async function () {
            const worker = await spawn(BlobWorker.fromText(WorkerText));
            console.log(await worker("Hello, World!"));
            await Thread.terminate(worker);
        },
    },
});
</script>
```

## Configuration Details
- Node: `16.13.2`
- Yarn: `1.22.17`
- Threads: `1.7.0`
- Rollup-plugin-threads: `1.2.0`
- Typescript: `4.5.5`
- Vite: `2.8.3`
- Rollup: `2.67.2`
- Electron: `16.0.9`

My Rollup configuration file is nested in the `vite.js` file I use to configure Vite itself, but it is below:

```js
// vite.js
const Path = require("path");
const { createVuePlugin } = require("vite-plugin-vue2");
const { defineConfig } = require("vite");
const threads = require("rollup-plugin-threads");
const urlResolve = require("rollup-plugin-url-resolve");
const commonjs = require("@rollup/plugin-commonjs");
const resolve = require("@rollup/plugin-node-resolve");

/**
 * https://vitejs.dev/config
 */
const config = defineConfig({
    root: Path.join(__dirname, "..", "src", "renderer"),
    publicDir: "public",
    server: {
        port: 8080,
    },
    open: false,
    build: {
        outDir: Path.join(__dirname, "..", "build", "renderer"),
        emptyOutDir: true,
    },
    plugins: [
        threads.default({
            plugins: [resolve.default(), commonjs(), createVuePlugin()],
            verbose: true,
            include: ["../src/**/Worker.ts"],
            external: ["events", "os", "path", "tty", "util"],
        }),
        createVuePlugin(),
        urlResolve(),
    ],
    resolve: {
        alias: {
            "@": Path.join(__dirname, "..", "src", "renderer"),
        },
    },
    external: ["child_process", "events", "os", "path", "tty", "util"],
});

module.exports = config;

```

If there is anything else you need to know, let me know and I will do my best to provide what is requested.

**Comment by Wakeful-Cloud** [comment]
I believe you're correct - the parent Rollup bundler (Vite) is bundling the worker, not the child bundler.

I'm a bit suspicious of the `include` option. Can you post the full build output (Especially containing the `Bundling worker at`... lines)? That way, we can confirm your hypothesis. If you don't see that line in the logs, you may want to update the plugin's config to :
```javascript
include: [Path.join(__dirname, "..", "src", "**", "Worker.ts"]
```

**Comment by jmc07712** [comment]
Hi, sorry for the inactivity. I have changed the `include` path to what you have suggested, but I am still getting the output you requested regarding the build process for the rollup plugin. This may be due to Vite, and the way the build process is configured with the `Main` and `Renderer` process being bundled together in different steps.

The only output I can get is from the `expose called in master thread` error which I will post below:

```sh
Error: expose() called in the master thread.
    at expose (W:\Lab\exp\electron-vue-template\node_modules\threads\dist\worker\index.js:146:15)
    at Object.<anonymous> (W:\Lab\exp\electron-vue-template\build\main\Worker.js:6:22)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (W:\Lab\exp\electron-vue-template\build\main\main.js:19:34)
```

Let me know if this helps. I can try and dig further for more output, but in my initial exploration, it seems like things are a little bit "hidden" for lack of a better word.

**Comment by Wakeful-Cloud** [comment]
I admittedly haven't tried Vite with this plugin but have you tried setting [Vite's `logLevel`](https://vitejs.dev/config/#loglevel)? We're looking for a log entry along the lines of `[Threads Plugin 📦] Bundling worker at /full/path/to/worker/entrypoint`.

**Comment by Wakeful-Cloud** [comment]
Closing due to inactivity.
